title: Force of Future
anthor: Jie Nissel
email: jie.gsu@gmail.com
description: It is a site for learning and recording ML/AI/NLP applications. 
linkedin_username: Jie Nissel

theme: jekyll-theme-cayman
markdown: kramdown
